/lc_vision:
  ros__parameters:
    sdk_root: /home/betty/AstraSDK-v2.1.3-Linux-arm/AstraSDK-v2.1.3-94bca0f52e-20210611T023312Z-Linux-aarch64

    rgb.enable: true
    rgb.width: 640
    rgb.height: 480
    rgb.capture_fps: 15
    rgb.publish_fps: 10
    rgb.bitrate_kbps: 1200
    rgb.gop_size: 30
    rgb.frame_id: cam_link

    depth.enable: true
    depth.width: 640
    depth.height: 480
    depth.capture_fps: 15
    depth.publish_fps: 8
    depth.bitrate_kbps: 500
    depth.gop_size: 24
    depth.frame_id: cam_link
    depth.visualization_min_mm: 300
    depth.visualization_max_mm: 5000
    depth.invalid_as_black: true

    detector.enable: true
    detector.backend: auto
    detector.model_dir: models/yolo26n_ncnn_model
    detector.input_size: 640
    detector.score_threshold: 0.25
    detector.nms_threshold: 0.45
    detector.fps: 5
    detector.vulkan_device_index: 0
    detector.cpu_num_threads: 2
    detector.log_backend_info: true
    detector.target_classes: ["person"]
